### ISSUE TITLE
handle calc()

### ISSUE THREAD

**Issue by VinSpee** [jxnblk/css-scss#8]
Hi, great work on this project.

It appears as though currently, `calc()` is converted to a sass calculation, however, this isn't always possible. For example, this input:

`margin-left: calc(-50vw + 50%);`

is converted to

`margin-left (-50vw + 50%);`

which obviously throws

> Error: Incompatible units: '%' and 'vw'.

to solve this, postcss-calc uses [reduce-css-calc](https://github.com/MoOx/reduce-css-calc). Any opposition to another dependency?

**Comment by jxnblk** [comment]
I haven't really done much maintenance to this package, but would definitely accept a PR if that plugin works. Wouldn't it just remove any notion of Sass calculations though?

**Comment by VinSpee** [comment]
Yes, that is a complication.
